use daku;
#CREATING A TABLE
create table TABLE1(
NAME varchar(50) PRIMARY KEY,
DEPARTMENT varchar(20)
);
#CREATING ANOTHER TABLE
create table TABLE2(
ID INT(10),
SALARY NUMERIC(20)
);
#INSERTING VALUES IN TABLE 1
INSERT INTO TABLE1 VALUES
 ('OWASHIM','EE'),
 ('ROHIT','IT'),
('RAHUL','IT'),
('SAM','FINANCE'),
('TOM','OPERATOR');

#INSERTING VALUES IN TABLE 2
INSERT INTO TABLE2 VALUES
(1,30000),
(2,50000),
(3,20000),
(4,25000),
(5,10000);

SELECT NAME,DEPARTMENT,ID,SALARY FROM TABLE1 FULL JOIN TABLE2;
