USE daku;
#CREATING EMP1 TABLE
CREATE TABLE EMP1(
ID INT(2),
EMP1_NAME VARCHAR(10),
BASIC FLOAT(6,2),
DESIGNATION VARCHAR(10),
AGE NUMERIC(2)
);
#UPDATING BASIC
ALTER TABLE EMP1
MODIFY COLUMN BASIC INT(10);
#UPDATING EMP_NAME
ALTER TABLE EMP1
MODIFY COLUMN EMP1_NAME VARCHAR(15);
#CREATING TABLE EMP_TRAINEE
CREATE TABLE EMP_TRAINEE(
EMP_TRAINEE_ID INT (2),
EMP_TRAINEE_NAME VARCHAR(15),
EMP_TRAINEE_BASIC INT (10),
EMP_TRAINEE_AGE INT (2));
#ADDING VALUES
INSERT INTO EMP1 VALUES
('01','ROHIT','6700','MANAGER','24'),
('02','SUNIL','6200','ENGNIEER','27'),
('03','PAYAL','6300','ENGNIEER','25'),
('04','KUNAL','6700','TRAINEE','28'),
('05','SUNITA','6230','TRAINEE','26'),
('06','BIMAL','7000','TRAINEE','25');
#INSERTING ALL VALUES TO EMP_TRAINEE
INSERT INTO EMP_TRAINEE SELECT * FROM EMP1;
#DISPLAYING BOTH TABLES
SELECT * FROM EMP1, EMP_TRAINEE;
#ADDING COLOUMNS
ALTER TABLE EMP1 ADD SKILL VARCHAR (10) AFTER BASIC;
alter TABLE EMP1 ADD DOJ DATE AFTER AGE;
#ADDING VALUES USING CONDITIONS
UPDATE EMP1 SET SKILLS='JAVA' WHERE ID = 01;
UPDATE EMP1 SET SKILLS='PYTHON' WHERE ID = 02;
UPDATE EMP1 SET SKILLS='SQL' WHERE ID = 03;
UPDATE EMP1 SET SKILLS='C++' WHERE ID = 04;
UPDATE EMP1 SET SKILLS='JAVA_S' WHERE ID = 05;
UPDATE EMP1 SET SKILLS='C' WHERE ID = 06;
UPDATE EMP1 SET DOJ='12-04-1997' WHERE ID = 01;
UPDATE EMP1 SET DOJ='12-04-1996' WHERE ID = 02;
UPDATE EMP1 SET DOJ='12-04-1999' WHERE ID = 03;
UPDATE EMP1 SET DOJ='12-04-2000' WHERE ID = 04;
UPDATE EMP1 SET DOJ='12-04-2001' WHERE ID = 05;
UPDATE EMP1 SET DOJ='12-04-2002' WHERE ID = 06;
#UPDATING DESIGNATION
ALTER TABLE EMP_TRAINEE
MODIFY DESIGNATION VARCHAR (10);
#UPDATING DESIGNATION
UPDATE EMP_TRAINEE SET DESIGNATION = 'PROGRAMMER TRAINEE';
#UPDATING ID
ALTER TABLE EMP1
MODIFY ID VARCHAR (5);
#DISPLAYING BOTH TABLES
SELECT * FROM EMP1, EMP_TRAINEE;
#UPDATING AGE
ALTER TABLE EMP1 RENAME COLUMN AGE TO AGE_IN_YEARS;
#DELETING TRAINEE DETAILS
DELETE FROM EMP1 WHERE DESIGNATION = 'TRAINEE';
#delete AGE
ALTER TABLE EMP_TRAIMEE DROP COLUMN AGE;
#DELETE 2 COLOUMNS
ALTER TABLE EMP_TRAINEE DROP column EMP_TRAINEE_BASIC,DROP column EMP_TRAINEE_ID;
#RENAME
ALTER TABLE EMP1 RENAME EMP_MGE_EGR;
#DELETE EMP_TRAINEE
DROP TABLE EMP_TRAINEE;
#DELETE DETAILS FROM EMP_MGR_ENGR
truncate EMP_MGR_ENGR;
#RECOVER
ROLLBACK;
 

  
